apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: ghtorrent
spec:
  serviceName: mongo-hs
  replicas: 3
  template:
    metadata:
      labels:
        app: mongo
        replicaset: MainRepSet
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - mongo
              topologyKey: "kubernetes.io/hostname"
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongod-container
          image: mongo
          command:
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
            - "--auth"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: zfs-storage
      selector:
        matchLabels:
          app: mongo
      resources:
        requests:
          storage: 20Gi
